config/routes.rb
Spendful::Application.routes.draw do
  
  mount StripeEvent::Engine => '/stripe-webhook'
  
  scope "onboarding" do
    get "" => "onboarding#new", :as => "new_onboarding"
    post "step1" => "onboarding#step1", :as => "step1_onboarding"
    post "step2" => "onboarding#step2", :as => "step2_onboarding"
    post "finish" => "onboarding#finish", :as => "finish_onboarding"
  end
	
  resources :budgets do
    resources :transactions
    resources :items do
      resources :transactions
    end
  end
  
  post "feedback" => "feedback#create", :as => "feedback"
  
  scope "account" do
    resources :subscriptions
    post "payment" => "subscriptions#payment", :as => "subscription_payment"
    get     ""  => "users#edit",  :as => "account"
    put    ""  => "users#update",    :as => "account"
    delete  ""  => "users#destroy", :as => "account"
  end

	get "logout" => "sessions#destroy", :as => "logout"
	
  scope "login" do
    get   ""   =>  "sessions#new",     :as => "login"
    post  ""   =>  "sessions#create",  :as => "login"
    get   "password" => "passwords#new",     :as => "forgot_password"
    post  "password" => "passwords#create",  :as => "forgot_password"
    get   "password/reset(/:id)" => "passwords#show", :as => "reset_password"
    put   "password/reset(/:id)" => "passwords#update", :as => "reset_password"
  end

  get "signup" => "users#new", :as => "signup"
  post "signup" => "users#create", :as => "signup"
  
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  match "/500", :to => "errors#internal_server_error"
  match "/404", :to => "errors#not_found", :as => 'not_found'

  root :to => "pages#index"

  match ":action", :controller => "pages"

end

app/views/shared/_flashes.html.haml
- if flash.any?
  - flash.each do |key, value|
    #flash.alert.alert-block{:class => "#{key.to_s == 'notice' ? 'alert-info' : 'alert-error'}"}
      %strong= value

app/views/shared/_footer.html.haml
.nav-pages.nav

  = link_to t("home.action"), root_path
  
  - if logged_in?
  
    - if budgets?
      = link_to t("budget.action"), budgets_path
    - else
      = link_to t("budgets.new.action"), budgets_path
    = link_to t("account.action"), account_path

  - else
  
    = link_to t("login.action"), login_path
    = link_to t("signup.action"), signup_path

  -#
    .legal
      = link_to t("terms.action"), terms_path
      = link_to t("privacy.action"), privacy_path

%p.copyright
  &copy;#{Date.today.year}
  = t("domain")

app/views/shared/_form-errors.html.haml
- if object.errors.any?
  .form-errors.alert.alert-error
    %strong= "#{pluralize(object.errors.count, "error")} prohibited this from being saved:"
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/shared/_header.html.haml
- if budget?

  %h1.budget-title= @budget.name

  %ul.navigation.nav-dates
    
    - if (@date_end - 1.month) > @budget.beginning
      %li
        %a.button.button-large.button-dark.icon.previous{:href => budget_path(@budget, {:month => (@date_beginning - 1.month).month, :year => (@date_beginning - 1.month).year})}
          %span.glyphicon.icon-white.glyphicon-arrow-left
    - else
      %li
        %a.button.button-large.button-dark.icon.previous.disabled{:href => budget_path(@budget, {:month => @date_beginning.month, :year => @date_beginning.year})}
          %span.glyphicon.icon-white.glyphicon-arrow-right
        
    - if (@date_beginning + 1.month) > @budget.beginning
      %li
        %a.button.button-large.button-dark.icon.next{:href => budget_path(@budget, {:month => (@date_beginning + 1.month).month, :year => (@date_beginning + 1.month).year})}
          %span.glyphicon.icon-white.glyphicon-arrow-right
  
    - if @today > @date_end || @today < @date_beginning
      %li
        %a.button.button-large.button-dark.today{:href => budget_path(@budget, {:month => @today.month, :year => @today.year})}= t("date.today")
  
  %h2.dates
    %strong= @date_beginning.day
    = @date_beginning.strftime("%b")
    &mdash;
    %strong= @date_end.day
    = @date_end.strftime("%b")
    %span.light= @date_end.year

- else

  - if budgets?
  
    %ul.navigation.nav-back
      %a.button.button-light{:href => budgets_path}
        %span.glyphicon.glyphicon-arrow-left
        = t("budget.action")
        
  - elsif params[:action] != "new" && params[:action] != "create"
  
    %ul.navigation.nav-back
      %li
        %a.button.button-light{:href => new_budget_path}
          %span.glyphicon.glyphicon-plus
          = t("budgets.new.action")

.navigation.dropdown.nav-account
  %li.dropdown
    %a.button.button-large.button-light.icon.dropdown-toggle{:href => "#", :data => {:toggle => "dropdown"}}
      %span.glyphicon.glyphicon-user
      %b.caret
    %ul.dropdown-menu
      - if current_user.trial?
        %li= link_to "Upgrade to Premium", new_subscription_path
      - else
        %li= link_to "Premium", subscriptions_path
      %li= link_to t("account.action"), account_path
      %li= link_to t("logout"), logout_path