config/routes.rb
Spendful::Application.routes.draw do
  
  mount StripeEvent::Engine => '/stripe-webhook'
  
  scope "onboarding" do
    get "" => "onboarding#new", :as => "new_onboarding"
    post "step1" => "onboarding#step1", :as => "step1_onboarding"
    post "step2" => "onboarding#step2", :as => "step2_onboarding"
    post "finish" => "onboarding#finish", :as => "finish_onboarding"
  end
	
  resources :budgets do
    resources :transactions
    resources :items do
      resources :transactions
    end
  end
  
  post "feedback" => "feedback#create", :as => "feedback"
  
  scope "account" do
    resources :subscriptions
    post "payment" => "subscriptions#payment", :as => "subscription_payment"
    get     ""  => "users#edit",  :as => "account"
    put    ""  => "users#update",    :as => "account"
    delete  ""  => "users#destroy", :as => "account"
  end

	get "logout" => "sessions#destroy", :as => "logout"
	
  scope "login" do
    get   ""   =>  "sessions#new",     :as => "login"
    post  ""   =>  "sessions#create",  :as => "login"
    get   "password" => "passwords#new",     :as => "forgot_password"
    post  "password" => "passwords#create",  :as => "forgot_password"
    get   "password/reset(/:id)" => "passwords#show", :as => "reset_password"
    put   "password/reset(/:id)" => "passwords#update", :as => "reset_password"
  end

  get "signup" => "users#new", :as => "signup"
  post "signup" => "users#create", :as => "signup"
  
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  match "/500", :to => "errors#internal_server_error"
  match "/404", :to => "errors#not_found", :as => 'not_found'

  root :to => "pages#index"

  match ":action", :controller => "pages"

end

app/views/pages/_aside.html.haml
.aside

  .nav.nav-pills
    = link_to t("home.title"), root_path
    = link_to t("terms.title"), terms_path, :class => "#{"active" if @active == "terms"}"
    = link_to t("privacy.title"), privacy_path, :class => "#{"active" if @active == "privacy"}"

app/views/pages/_header.html.haml
= link_to image_tag("shared/logo-spendful.png", :alt => t("brand"), :size => "125x50"), root_path, :class => "brand"

.navbar-header
  
  %button{:class => "navbar-toggle collapsed", "data-toggle" => "collapse", "data-target" => "navbar-collapse"}
    
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar

.collapse.navbar-collapse

  %ul.nav.nav-primary.pull-right
    
    %li
      = link_to t("home.action"), root_path

    - if logged_in?
    
      - if budgets?
        %li
          = link_to t("budget.action"), budget_path((@budget || current_user.budgets.first))
      - else
        %li
          = link_to t("budgets.new.action"), budgets_path
      %li
        = link_to t("account.action"), account_path

    - else
    
      %li
        = link_to t("login.action"), login_path
      %li
        = link_to t("signup.action"), signup_path

app/views/pages/index.html.haml
- @body_class = "homepage"

- content_for :assets do
  = stylesheet_link_tag "pages/homepage"
  -#= javascript_include_tag "pages/homepage"


.row

  #introduction

    .container

      %h1.heading
        Your money
        %span.light
          &mdash;
          today, and in the future.

      %img.screenshot{:src => image_path("pages/home/screenshot1.png")}
      
      %ul.benefits
        %li
          Learn where you spend money
        %li
          See your balance, months from now
        %li
          Know how much you need to save

      %a.button.button-positive.signup{:href => signup_path}
        Try it for free
        %span.glyphicon.glyphicon-arrow-right.icon-white

  .container

    .row.features

      .col-md-4.feature
        %h2.heading Track
        %p
          Tracking your money
          %strong removes the mystery
          of where you spent it all.

      .col-md-4.feature
        %h2.heading Budget
        %p
          A budget makes sure you can
          %strong pay for everything
          you need to.

      .col-md-4.feature
        %h2.heading Forecast
        %p
          Instantly see how changes to your budget 
          %strong affects your future
          finances.

    .row.details

      %img.screenshot{:src => image_path("pages/home/screenshot2.png")}

      .section.col-md-12

        %h3.heading
          What can 
          %strong
            you
          do with Spendful?

        %ul
          %li
            See all your past, and future finances in one page, month by month.
          %li
            Schedule re-occurring items, such as salary and regular bills.
          %li
            Group multiple transactions under a single item, e.g. "Groceries".
          %li
            See your money months or years into the future.

      .section.col-md-12

        %h3.heading
          We're all about 
          %strong
            Trust &amp; Security

        %ul.trust
          %li
            We don't require access to your bank account, or statements.
          %li
            Everything is private, none of your data is personally identifiable.


    .row.statistics

      .col-md-4.statistic
        %h4.heading
          10,000+
        %p
          &hellip;people in over 100 countries.

      .col-md-4.statistic
        %h4.heading
          &pound;182million+
        %p
          &hellip;in multiple currencies, every month.

      .col-md-4.statistic
        %h4.heading
          52,000+
        %p
          &hellip;items &amp; transactions per month.

    %a.cta{:href => signup_path}
      %strong Still not sure?
      It’s completely free, and you can get started in less than 30 seconds.

app/views/pages/privacy.html.haml
- title t("privacy.title")
- @active = "privacy"


.container

  = render :partial => "pages/aside"

  .content

    %h1= t("privacy.title")

    %p
      Awaiting content.

app/views/pages/terms.html.haml
- title t("terms.title")
- @active = "terms"


.container

  = render :partial => "pages/aside"

  .content

    %h1= t("terms.title")

    Awaiting content.