config/routes.rb
Spendful::Application.routes.draw do
  
  mount StripeEvent::Engine => '/stripe-webhook'
  
  scope "onboarding" do
    get "" => "onboarding#new", :as => "new_onboarding"
    post "step1" => "onboarding#step1", :as => "step1_onboarding"
    post "step2" => "onboarding#step2", :as => "step2_onboarding"
    post "finish" => "onboarding#finish", :as => "finish_onboarding"
  end
	
  resources :budgets do
    resources :transactions
    resources :items do
      resources :transactions
    end
  end
  
  post "feedback" => "feedback#create", :as => "feedback"
  
  scope "account" do
    resources :subscriptions
    post "payment" => "subscriptions#payment", :as => "subscription_payment"
    get     ""  => "users#edit",  :as => "account"
    put    ""  => "users#update",    :as => "account"
    delete  ""  => "users#destroy", :as => "account"
  end

	get "logout" => "sessions#destroy", :as => "logout"
	
  scope "login" do
    get   ""   =>  "sessions#new",     :as => "login"
    post  ""   =>  "sessions#create",  :as => "login"
    get   "password" => "passwords#new",     :as => "forgot_password"
    post  "password" => "passwords#create",  :as => "forgot_password"
    get   "password/reset(/:id)" => "passwords#show", :as => "reset_password"
    put   "password/reset(/:id)" => "passwords#update", :as => "reset_password"
  end

  get "signup" => "users#new", :as => "signup"
  post "signup" => "users#create", :as => "signup"
  
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  match "/500", :to => "errors#internal_server_error"
  match "/404", :to => "errors#not_found", :as => 'not_found'

  root :to => "pages#index"

  match ":action", :controller => "pages"

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  attr_accessible :user_id, :reference, :plan, :started_on, :expires_on, :cancelled_on, :card_type, :card_last4, :card_name

  belongs_to :user

  validate :validation_process

  def active?
    grace_period = Constants::Subscriptions::GRACE_PERIOD
    self.expires_on > (Date.today + grace_period) && self.cancelled_on.nil?
  end

  def in_grace_period?
    grace_period = Constants::Subscriptions::GRACE_PERIOD
    self.expires_on > Date.today && self.expires_on < (Date.today + grace_period) && self.cancelled_on.nil?
  end

  def expired?
    grace_period = Constants::Subscriptions::GRACE_PERIOD
    self.expires_on < (Date.today + grace_period) || self.cancelled_on.present?
  end

  def cancelled?
    self.cancelled_on.present?
  end

  def status
    return Constants::Subscriptions::STATUS_IN_GRACE_PERIOD if self.in_grace_period?
    return Constants::Subscriptions::STATUS_EXPIRED if self.expired?
    return Constants::Subscriptions::STATUS_CANCELLED if self.cancelled?
    Constants::Subscriptions::STATUS_ACTIVE
  end # def status

  protected

  def validation_process
    validate_started_on
    validate_expires_on
    validate_cancelled_on
    validate_current_subscription
  end

  private

  def validate_started_on
    return unless self.started_on
    self.errors.add :started_on, 'cannot be in the future' if self.started_on > Date.today
  end

  def validate_expires_on
    return unless self.started_on && self.expires_on
    self.errors.add :expires_on, 'must be after started on' unless self.expires_on > self.started_on
  end

  def validate_cancelled_on
    return unless self.started_on && self.cancelled_on
    self.errors.add :cancelled_on, 'cannot be before started on' if self.cancelled_on < self.started_on
  end

  def validate_current_subscription
    return if self.expired? || self.cancelled?

    other_subscriptions = self.user.subscriptions - [self]
    if other_subscriptions.any? { |subscription| subscription.active? }
      self.errors.add :base, Constants::Subscriptions::ALREADY_CURRENT_SUBSCRIPTION_ERROR
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  skip_before_filter :check_subscription, :only => [:index, :new, :payment, :create]

  def index
    redirect_to(new_subscription_path) unless self.current_user.subscriptions.any?
  end

  def new
    redirect_to(subscriptions_path) if self.current_user.premium?
    @plans = []
    Constants::Subscriptions::PLANS.each do |plan|
      @plans.push ["#{plan[:name]} &mdash; &pound;#{plan[:amount]}".html_safe, plan[:id]]
    end
  end
  
  def payment
    redirect_to(subscriptions_path) if self.current_user.premium?
    @plan = params[:plan]
  end

  def create
    redirect_to(subscriptions_path) if self.current_user.premium?
    
    token = params[:stripeToken]
    plan = Constants::Subscriptions::PLANS.reject{ |p| p if p[:id] != params[:plan] }[0]
    
    
    customer = Stripe::Customer.create(
      :card => token,
      :plan => plan[:id],
      :email => current_user.email
    )
    
    @subscription = current_user.subscriptions.new({
      :plan => plan[:id],
      :reference => customer.id,
      :started_on => Date.today,
      :expires_on => Date.today + 1.day,
      :card_type => customer.active_card.type,
      :card_last4 => customer.active_card.last4,
      :card_name => customer.active_card.name
    })
    
    @user = self.current_user
    @user.update_personal({
      :name => params[:name],
      :address_line1 => params[:address_line1],
      :address_line2 => params[:address_line2],
      :address_city => params[:address_city],
      :address_zip => params[:address_zip],
      :country => params[:country]
    })
    self.current_user = @user
    
    if @subscription.save
      flash[:notice] = "You now have Spendful Premium!"
      redirect_to subscriptions_path
    else
      flash[:error] = "There was a problem starting your subscription"
      render :payment
    end
  end
  
  def destroy
    @subscription = current_user.subscriptions.find(params[:id])
    # customer = Stripe::Customer.retrieve(@subscription.reference)
    # customer.delete
    @subscription.update_attributes({:cancelled_on => Date.today})
    flash[:notice] = "Your Premium subscription has been cancelled"
    redirect_to subscriptions_path
  end

end

app/views/subscriptions/index.html.haml
- title "Spendful Premium"
- @body_class = "subscriptions"

- content_for :assets do
  = stylesheet_link_tag "pages/subscriptions"

.container

  %table
    - current_user.subscriptions.each do |subscription|
      %tr
        %th Started on
        - if subscription.expired?
          %th Last renewal
          %th Cancelled
        - else
          %th{:colspan => 2} Next renewal
        %th Card Name
        %th Card Type
        %th Card Number
        %th.actions{:colspan => 2} Status
      %tr
        %td= subscription.started_on
        - if subscription.expired?
          %td= subscription.expires_on
          %td= subscription.cancelled_on
        - else
          %td{:colspan => 2}= subscription.expires_on
        %td= subscription.card_name
        %td= subscription.card_type
        %td
          **** **** ****
          = subscription.card_last4
        %td.status
          = "Active" if subscription.active?
          = "Pending" if subscription.in_grace_period?
          = "Expired" if subscription.expired?
        %td.actions
          - if !subscription.expired?
            = link_to "Cancel", subscription_path(subscription), :method => "delete", :confirm => "Are you sure?", :class => "button button-primary"
      %tr
        %th.spacer{:colspan => 8} &nbsp;
    
  - if current_user.trial?
    = link_to "Upgrade to Premium", new_subscription_path, :class => "button button-primary"

app/views/subscriptions/new.html.haml
- title "Upgrade to Spendful Premium"
- @body_class = "subscription new-subscription"

- content_for :assets do
  = stylesheet_link_tag "pages/subscription"

.container

  .col-md-6.col-md-offset-3.form-box

    - if current_user.trial_days_left >= 0
      %h1.heading
        Upgrade to Premium
    
      %p You can upgrade to Spendful Premium at anytime.
      
      %p
        We really hope you've had enough time to try it out, and if you find it useful we'd like to ask you to pay something towards it's upkeep so we can make it even better. Remember, you can give us feedback on any improvements you'd like to see using the form on the bottom of the budget page, or email the owner - 
        %a{:href => "mailto:mitchell@spendful.com"} mitchell@spendful.com
    
    - else
      %h1.heading
        Thank you for trying out Spendful.
    
      %p We hope you have had enough time to try it out.
      %p To continue using Spendful, you must upgrade to Spendful Premium.
    
    = form_tag subscription_payment_path, {:method => "post", :class => "form-horizontal", :novalidate => "true", :autocomplete => "off"} do

      .form-group
        = label_tag :plan, "Payment Plan", :class => "control-label"
        .controls
          = select_tag :plan, options_for_select(@plans)

      .form-actions
        %button.button.button-primary{:type => "submit"}= t("actions.continue")

app/views/subscriptions/payment.html.haml
- title "Spendful Premium Payment"
- @body_class = "subscription"

- content_for :assets do
  = stylesheet_link_tag "pages/subscription"
  = javascript_include_tag "pages/payment"
  = javascript_include_tag "https://js.stripe.com/v2/"

:javascript
  Stripe.setPublishableKey("#{STRIPE_PUBLIC_KEY}");

.container

  .col-md-6.col-md-offset-3.form-box

    %h1.heading
      Secure Payment
    
    = form_tag subscriptions_path, {:method => "post", :class => "form-horizontal", :novalidate => "true", :autocomplete => "off", :id => "payment-form"} do

      .payment-errors.form-errors.alert.alert-error.hide
      
      = hidden_field_tag :plan, @plan

      .form-group
        = label_tag :name, "Name on Card", :class => "control-label"
        .controls
          = telephone_field_tag :name, "", :data => {:stripe => "name"}

      .form-group
        = label_tag :address_line1, "House Name/Number", :class => "control-label"
        .controls
          = telephone_field_tag :address_line1, "", :data => {:stripe => "address_line1"}

      .form-group
        = label_tag :address_line2, "Street", :class => "control-label"
        .controls
          = telephone_field_tag :address_line2, "", :data => {:stripe => "address_line2"}

      .form-group
        = label_tag :address_city, "City/Town", :class => "control-label"
        .controls
          = telephone_field_tag :address_city, "", :data => {:stripe => "address_city"}

      .form-group
        = label_tag :address_zip, "Postcode/Zip", :class => "control-label"
        .controls
          = telephone_field_tag :address_zip, "", :data => {:stripe => "address_zip"}
          
      .form-group
        = label_tag :country, "Country", :class => "control-label"
        .controls
          = select_tag :country, options_for_select([["Choose one...", nil]]) + country_options_for_select

      .form-group
        = label_tag :number, "Credit Card Number", :class => "control-label"
        .controls
          = telephone_field_tag :number, "", :data => {:stripe => "number"}

      .form-group
        = label_tag :cvc, "CVC", :class => "control-label"
        .controls
          = telephone_field_tag :cvc, "", :data => {:stripe => "cvc"}

      .form-group
        = label_tag :expiration, "Expiration", :class => "control-label"
        .controls
          = select_tag :expiration_month, options_for_select((1..12).map {|n| "%02d" % n}), :data => {:stripe => "exp-month"}, :class => "expiration-month"
          = select_tag :expiration_year, options_for_select((Date.today.year..(Date.today.year + 10)).map {|n| "%02d" % n}), :data => {:stripe => "exp-year"}, :class => "expiration-year"

      .form-actions
        %button.button.button-primary{:type => "submit"} Pay