config/routes.rb
Spendful::Application.routes.draw do
  
  mount StripeEvent::Engine => '/stripe-webhook'
  
  scope "onboarding" do
    get "" => "onboarding#new", :as => "new_onboarding"
    post "step1" => "onboarding#step1", :as => "step1_onboarding"
    post "step2" => "onboarding#step2", :as => "step2_onboarding"
    post "finish" => "onboarding#finish", :as => "finish_onboarding"
  end
	
  resources :budgets do
    resources :transactions
    resources :items do
      resources :transactions
    end
  end
  
  post "feedback" => "feedback#create", :as => "feedback"
  
  scope "account" do
    resources :subscriptions
    post "payment" => "subscriptions#payment", :as => "subscription_payment"
    get     ""  => "users#edit",  :as => "account"
    put    ""  => "users#update",    :as => "account"
    delete  ""  => "users#destroy", :as => "account"
  end

	get "logout" => "sessions#destroy", :as => "logout"
	
  scope "login" do
    get   ""   =>  "sessions#new",     :as => "login"
    post  ""   =>  "sessions#create",  :as => "login"
    get   "password" => "passwords#new",     :as => "forgot_password"
    post  "password" => "passwords#create",  :as => "forgot_password"
    get   "password/reset(/:id)" => "passwords#show", :as => "reset_password"
    put   "password/reset(/:id)" => "passwords#update", :as => "reset_password"
  end

  get "signup" => "users#new", :as => "signup"
  post "signup" => "users#create", :as => "signup"
  
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  match "/500", :to => "errors#internal_server_error"
  match "/404", :to => "errors#not_found", :as => 'not_found'

  root :to => "pages#index"

  match ":action", :controller => "pages"

end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController
  
  def new
  end

	def step1
		@old_budget = current_user.budgets.find_by_slug("personal")
		redirect_to budget_path(@old_budget, :params => {:tour => true}) and return if @old_budget
    @budget = current_user.budgets.create({:name => "Personal", :initial_balance => 0})
    @item = @budget.items.new
    @item.starts_on = Date.today
    @item.amount = 100000
	end
  
  def step2
    @budget = current_user.budgets.find(params[:budget_id])
    
    params[:item][:amount] = money_to_integer(params[:item][:amount])
    @budget.items.create(params[:item])
    @item = @budget.items.new
    @item.starts_on = Date.today
    @item.amount = 10000
  end
  
  def finish
    @budget = current_user.budgets.find(params[:budget_id])
    
    params[:item][:amount] = money_to_integer(params[:item][:amount])
    @budget.items.create(params[:item])
    
    redirect_to budget_path(@budget, :params => {:tour => true})
  end

end

app/views/onboarding/new.html.haml
- title "Spendful Tour"
- @body_class = "onboarding"

- content_for :assets do
  = stylesheet_link_tag "pages/onboarding"
  = javascript_include_tag "pages/onboarding"


.container

  .row
    
    .col-md-6.col-md-offset-3
  
      %h1.heading
        Would you like a quick introduction to how Spendful works?

      %p
        We'll guide you through the basics, and it will take about 2 minutes.

      .actions
        = link_to "Yes, Let's go!", step1_onboarding_path, :method => "post", :class => "button button-primary"

        %a.button{:href => new_budget_path} No, thanks

app/views/onboarding/step1.html.haml
- title "Spendful Tour"
- @body_class = "onboarding"

- content_for :assets do
  = stylesheet_link_tag "pages/onboarding"
  = javascript_include_tag "pages/onboarding"

.container

  .row
    
    .col-md-6.col-md-offset-3
  
      %h1.heading
        Add one type of income you receive
  
      %p
        We call this an "Income item". A budget is made up of lots of income and expense items, they can appear once or occur many times. The amount you enter for a budget item is a best guess at how much that income will receive or expense will cost you.

      = form_for [@budget, @item], :url => step2_onboarding_path, :html => {:class => "form-horizontal", :novalidate => "true"} do |form|

        = render :partial => "shared/form-errors", :locals => {:object => @item}
      
        = form.hidden_field :category, :value => "income"
        = hidden_field_tag :budget_id, @budget.id

        .form-group
          = form.label :name, :class => "control-label"
          .controls
            = form.text_field :name, :value => "Salary"
            %p.help-block
              You can change this to anything you like

        .form-group
          = form.label :amount, :class => "control-label"
          .controls
            = form.phone_field :amount, :value => cents_to_money(@item.amount)
            %p.help-block
              Estimate how much it will be
  
        .form-group
          = form.label :starts_on, :class => "control-label"
          .controls
            = form.text_field :starts_on, :value => (@item.starts_on.try(:strftime, "%d/%m/%Y")), :class => "date"
            %p.help-block
              Choose the first day this month that it's most likely to be paid to you

        .form-group
          = form.label :schedule, :class => "control-label"
          .controls
            = form.select :schedule, Constants::Items::SCHEDULES.map{ |s| [s.capitalize, s] }
            %p.help-block
              This is handy for income that is paid to you on a regular basis

        .form-actions
          %button.button.button-primary{:type => "submit"}= t("actions.save")
  

app/views/onboarding/step2.html.haml
- title "Spendful Tour"
- @body_class = "onboarding"

- content_for :assets do
  = stylesheet_link_tag "pages/onboarding"
  = javascript_include_tag "pages/onboarding"

.container

  .row
    
    .col-md-6.col-md-offset-3
  
      %h1.heading
        Add one type of expense
  
      %p
        We call this an "Expense item". You'll be able to add more income and expense items later. 
  
      = form_for [@budget, @item], :url => finish_onboarding_path, :html => {:class => "form-horizontal", :novalidate => "true"} do |form|

        = render :partial => "shared/form-errors", :locals => {:object => @item}
      
        = form.hidden_field :category, :value => "expense"
        = hidden_field_tag :budget_id, @budget.id

        .form-group
          = form.label :name, :class => "control-label"
          .controls
            = form.text_field :name, :value => "Groceries"
            %p.help-block
              You can change this to anything you like

        .form-group
          = form.label :amount, :class => "control-label"
          .controls
            = form.phone_field :amount, :value => cents_to_money(@item.amount)
            %p.help-block
              Estimate how much it will be
  
        .form-group
          = form.label :starts_on, :class => "control-label"
          .controls
            = form.text_field :starts_on, :value => (@item.starts_on.try(:strftime, "%d/%m/%Y")), :class => "date"
            %p.help-block
              Choose the first day this month that you're most likely to spend it

        .form-group
          = form.label :schedule, :class => "control-label"
          .controls
            = form.select :schedule, Constants::Items::SCHEDULES.map{ |s| [s.capitalize, s] }
            %p.help-block
              Change the schedule if it occurs more than once

        .form-actions
          %button.button.button-primary{:type => "submit"}= t("actions.save")
  